{% set name = "sphinx-versioned-docs" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-versioned-docs-{{ version }}.tar.gz
  sha256: 1fa444d70e392ceaf6269b5e38dc0a2f6a0a2f99d245ee4ea9e2b45d0e63f953

build:
  entry_points:
    - sphinx-versioned = sphinx_versioned.__main__:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.7
    - gitpython >=3.1.31
    - loguru >=0.7.0
    - setuptools >=66.0.0
    - sphinx >=4.6.0
    - typer >=0.9.0
    - rich

test:
  imports:
    - sphinx_versioned
  commands:
    - pip check
    - sphinx-versioned --help
  requires:
    - pip

about:
  home: https://github.com/devanshshukla99/sphinx-versioned-docs
  summary: Sphinx extension to build versioned docs.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - devanshshukla99
