{% set name = "sphinx-versioned-docs" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinx-versioned-docs-{{ version }}.tar.gz
  sha256: d060d7f6201ccc6d2db11a7c6f47dd0564a151b878a4a69aa4f94db4c4f835ca

build:
  entry_points:
    - sphinx-versioned = sphinx_versioned.__main__:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - gitpython >=3.1.31
    - loguru >=0.7.0
    - setuptools >=66.0.0
    - sphinx >=4.6.0
    - typer >=0.9.0
    - rich

test:
  imports:
    - sphinx_versioned
  commands:
    - pip check
    - sphinx-versioned --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/devanshshukla99/sphinx-versioned-docs
  summary: Sphinx extension to build versioned docs.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - devanshshukla99
